"""init

Revision ID: 228b0553766c
Revises: 
Create Date: 2026-04-11 15:53:00.055571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228b0553766c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_basic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('introduction', sa.String(length=200), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('fans_count', sa.Integer(), nullable=True),
    sa.Column('profile_photo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('relation', sa.Integer(), nullable=True),
    sa.Column('updata_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_relation')
    op.drop_table('user_basic')
    # ### end Alembic commands ###
